// import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import { Fredoka } from 'next/font/google';
const fredoka = Fredoka({
  subsets: ['latin'],
  weights: ['300', '400', '500', '600', '700'],
  variable: '--font-fredoka'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} antialiased light`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <div className="border-b w-full border-sidebar-border bg-sidebar p-2"><SidebarTrigger /></div>
            <div className="p-4">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
